manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/lucordes
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: unsecure
      import: app/west.yml
  self:
    path: config
