manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/lucordes
  projects:
    - name: zmk
      remote: lucordes
      revision: queue
      import: app/west.yml
  self:
    path: config
